apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "env-inspector.fullname" . }}
  labels:
    {{- include "env-inspector.labels" . | nindent 4 }}

data:
  APP_NAME: {{ .Values.config.APP_NAME | quote }}
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  AWS_REGION: {{ .Values.config.AWS_REGION | quote }}