apiVersion: v1
kind: Service

metadata:
  name: {{ include "env-inspector.fullname" . }}

  labels:
    {{- include "env-inspector.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app.kubernetes.io/name: {{ include "env-inspector.name" . }}

  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP