

apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "env-inspector.fullname" . }}

  {{- if .Values.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
  {{- end }}

  labels:
    {{- include "env-inspector.labels" . | nindent 4 }}